project_id = "fborsqajwdtjzvwgwppy"

[functions.send-telegram]
verify_jwt = false

[functions.test-telegram]
verify_jwt = false

[functions.daily-send]
verify_jwt = false

[functions.manage-settings]
verify_jwt = false

[functions.get-messages]
verify_jwt = false

[functions.get-stats]
verify_jwt = false
